# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalForecast',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mandi_name', models.CharField(default='Karnal Central APMC', max_length=150)),
                ('district', models.CharField(default='Karnal', max_length=100)),
                ('state', models.CharField(default='Haryana', max_length=100)),
                ('crop_name', models.CharField(default='Wheat (Sharbati)', max_length=150)),
                ('predicted_arrival_date', models.DateField()),
                ('predicted_volume_mt', models.DecimalField(decimal_places=2, default=3200.0, max_digits=10)),
                ('surge_risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Moderate Flow'), ('HIGH', 'High Surge Alert'), ('CRITICAL', 'Critical Overload')], default='HIGH', max_length=30)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=94.2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CongestionAlert',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mandi_name', models.CharField(default='Karnal Central APMC', max_length=150)),
                ('alert_level', models.CharField(choices=[('GREEN', 'Smooth Flow'), ('YELLOW', 'Approaching Quota'), ('RED', 'Traffic Stagnation Alert')], default='YELLOW', max_length=30)),
                ('recommended_action', models.TextField(default='Reroute non-perishable truck arrivals to Gharaunda Sub-Yard Lane 02.')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
