# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_string', models.CharField(max_length=50, unique=True)),
                ('farmer_name', models.CharField(default='Sardar Harpreet Singh', max_length=150)),
                ('mandi_name', models.CharField(default='Karnal Central APMC', max_length=150)),
                ('crop_name', models.CharField(default='Wheat (Sharbati)', max_length=150)),
                ('quantity_quintals', models.DecimalField(decimal_places=2, default=180.0, max_digits=10)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(default='09:00 AM - 11:00 AM', max_length=50)),
                ('lane', models.CharField(default='Lane 04 - Weighbridge A', max_length=100)),
                ('qr_image_base64', models.TextField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_tokens', to='slots.slotbooking')),
            ],
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate_pass_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(default='HR-05-AB-7821', max_length=30)),
                ('driver_name', models.CharField(default='Harpreet Singh', max_length=100)),
                ('security_guard', models.CharField(default='Balwant Singh (Gate 01)', max_length=100)),
                ('entry_allowed', models.BooleanField(default=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('qr_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_pass', to='tokens.qrtoken')),
            ],
        ),
    ]
