# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_number', models.CharField(max_length=50, unique=True)),
                ('farmer_name', models.CharField(default='Sardar Harpreet Singh', max_length=150)),
                ('farmer_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('mandi_name', models.CharField(default='Karnal Central Grain Yard', max_length=150)),
                ('state', models.CharField(default='Haryana', max_length=100)),
                ('district', models.CharField(default='Karnal', max_length=100)),
                ('commodity', models.CharField(default='Wheat (Sharbati)', max_length=150)),
                ('custom_commodity', models.CharField(blank=True, max_length=150, null=True)),
                ('is_custom_crop', models.BooleanField(default=False)),
                ('quantity_quintals', models.DecimalField(decimal_places=2, default=180.0, max_digits=10)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(default='09:00 AM - 11:00 AM', max_length=50)),
                ('lane', models.CharField(default='Lane 04 - Weighbridge A', max_length=100)),
                ('vehicle_number', models.CharField(default='HR-05-AB-7821', max_length=30)),
                ('driver_name', models.CharField(default='Harpreet Singh', max_length=100)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived at Gate'), ('WEIGHMENT', 'At Weighbridge'), ('INSPECTION', 'Quality Inspection'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=30)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_bookings', to='centers.procurementcenter')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_bookings_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(default='09:00 AM - 11:00 AM', max_length=50)),
                ('lane', models.CharField(default='Lane 04 - Weighbridge A', max_length=100)),
                ('max_capacity_quintals', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('booked_quintals', models.DecimalField(decimal_places=2, default=180.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='centers.procurementcenter')),
            ],
        ),
    ]
