# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQualityAnalysis',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_code', models.CharField(max_length=50, unique=True)),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='ai_quality_scans/')),
                ('crop_image_url', models.URLField(blank=True, null=True)),
                ('crop_name', models.CharField(default='Wheat (Sharbati)', max_length=150)),
                ('quality_score', models.DecimalField(decimal_places=2, default=94.5, max_digits=5)),
                ('estimated_moisture', models.DecimalField(decimal_places=2, default=11.1, max_digits=5)),
                ('defect_percentage', models.DecimalField(decimal_places=2, default=1.2, max_digits=5)),
                ('foreign_matter_estimate', models.DecimalField(decimal_places=2, default=0.7, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=99.2, max_digits=5)),
                ('is_preliminary', models.BooleanField(default=True)),
                ('ai_verdict', models.CharField(default='Preliminary Grade A (Optimal Dry Kernel Density)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_code', models.CharField(max_length=50, unique=True)),
                ('token_number', models.CharField(default='AGM-TK-99482', max_length=50)),
                ('farmer_name', models.CharField(default='Sardar Harpreet Singh', max_length=150)),
                ('crop_name', models.CharField(default='Wheat (Sharbati)', max_length=150)),
                ('mandi_name', models.CharField(default='Karnal Central APMC', max_length=150)),
                ('moisture_percentage', models.DecimalField(decimal_places=2, default=11.2, max_digits=5)),
                ('impurity_percentage', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('foreign_matter_percentage', models.DecimalField(decimal_places=2, default=0.6, max_digits=5)),
                ('broken_grains_percentage', models.DecimalField(decimal_places=2, default=1.1, max_digits=5)),
                ('quality_grade', models.CharField(default='Grade A', max_length=50)),
                ('result', models.CharField(choices=[('PASS', 'Pass & Approved for Mandi Procurement'), ('FAIL', 'Fail (Exceeds Tolerance Limits)'), ('CONDITIONAL', 'Conditional (Price Deduction Applicable)')], default='PASS', max_length=30)),
                ('remarks', models.TextField(default='Sample exceeds FAQ standard specifications. Optimal luster and dry weight.')),
                ('inspector_name', models.CharField(default='Dr. R. K. Sharma (Chief Quality Assayer)', max_length=150)),
                ('lab_equipment_id', models.CharField(default='NIR-OPTICAL-LAB-04', max_length=50)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
