# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropTraceability',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(default='BATCH-WHT-2026-9912', max_length=50)),
                ('crop_name', models.CharField(default='Wheat (Sharbati HD-3086)', max_length=150)),
                ('farmer_name', models.CharField(default='Sardar Harpreet Singh', max_length=150)),
                ('stage', models.CharField(choices=[('CROP_CREATED', 'Crop Harvest Sown & Declared'), ('LISTED', 'Listed in Marketplace'), ('OFFER_RECEIVED', 'Buyer Offer Received'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('AUCTION_WON', 'E-Auction Won by Trader'), ('TRANSPORT_BOOKED', 'Freight Truck Dispatched'), ('GATE_ENTRY', 'QR Gate Pass Verified at Mandi Yard'), ('WEIGHMENT', 'Tola Parchi Weighment Completed'), ('QUALITY_APPROVED', 'NIR Quality Grade A Certified'), ('WAREHOUSE_STORED', 'Stored in CWC Silo Complex'), ('PAYMENT_INITIATED', 'DBT Payment Disbursed via PFMS'), ('PAYMENT_COMPLETED', 'Credited to Farmer Bank Account')], default='PAYMENT_COMPLETED', max_length=50)),
                ('location', models.CharField(default='Karnal Central APMC / PNB Bank', max_length=150)),
                ('details', models.TextField(default='DBT ₹4,36,500 transferred to account ending in 1829. UTR: RBI056984210992')),
                ('verified_by', models.CharField(default='Govt of India Agri Stack', max_length=150)),
                ('blockchain_hash', models.CharField(default='0x7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
