# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(default='Sardar Harpreet Singh', max_length=150)),
                ('farmer_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('crop_name', models.CharField(default='Wheat (Sharbati)', max_length=150)),
                ('crop_name_hi', models.CharField(blank=True, default='गेहूं (सरबती)', max_length=150, null=True)),
                ('variety', models.CharField(default='HD-3086 Premium', max_length=150)),
                ('quantity_quintals', models.DecimalField(decimal_places=2, default=240.0, max_digits=10)),
                ('expected_price_per_qtl', models.DecimalField(decimal_places=2, default=2650.0, max_digits=10)),
                ('msp_rate', models.DecimalField(decimal_places=2, default=2425.0, max_digits=10)),
                ('quality_grade', models.CharField(default='Grade A', max_length=50)),
                ('moisture_pct', models.DecimalField(decimal_places=2, default=11.2, max_digits=5)),
                ('foreign_matter_pct', models.DecimalField(decimal_places=2, default=0.8, max_digits=5)),
                ('mandi_location', models.CharField(default='Karnal Central APMC', max_length=150)),
                ('district', models.CharField(default='Karnal', max_length=100)),
                ('state', models.CharField(default='Haryana', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Listing'), ('IN_AUCTION', 'Live in E-Auction'), ('RESERVED', 'Offer Accepted / Reserved'), ('SOLD', 'Sold & Completed')], default='ACTIVE', max_length=30)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerOffer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(default='ITC Agri Division', max_length=150)),
                ('buyer_company', models.CharField(default='ITC Agri Ltd', max_length=150)),
                ('buyer_phone', models.CharField(default='+91 99887 76655', max_length=20)),
                ('offered_price_per_qtl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_qty_quintals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_offer_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Farmer Review'), ('ACCEPTED', 'Accepted by Farmer'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_made', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.listing')),
            ],
        ),
    ]
