# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Baldev Singh', max_length=150)),
                ('phone', models.CharField(default='+91 94160 55421', max_length=20)),
                ('license_number', models.CharField(default='DL-05201948210', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(default='HR-05-AB-7821', max_length=30, unique=True)),
                ('vehicle_type', models.CharField(default='10-Wheeler Heavy Truck (25 MT)', max_length=50)),
                ('capacity_mt', models.DecimalField(decimal_places=2, default=25.0, max_digits=8)),
                ('current_location', models.CharField(default='Karnal GT Road', max_length=150)),
                ('current_latitude', models.DecimalField(decimal_places=6, default=29.6857, max_digits=9)),
                ('current_longitude', models.DecimalField(decimal_places=6, default=76.9905, max_digits=9)),
                ('is_available', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='logistics.driver')),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_code', models.CharField(max_length=50, unique=True)),
                ('commodity', models.CharField(default='Wheat (Grade A FAQ)', max_length=150)),
                ('quantity_mt', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('pickup_location', models.CharField(default='Karnal Central APMC Yard', max_length=150)),
                ('destination', models.CharField(default='Central Warehousing Corp (CWC) Silo 04, Panipat', max_length=150)),
                ('estimated_fare', models.DecimalField(decimal_places=2, default=8500.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_TRANSIT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_code', models.CharField(max_length=50, unique=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_eta', models.CharField(default='Today, 04:30 PM', max_length=100)),
                ('gps_status', models.CharField(default='Moving along NH-44 towards Panipat', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='logistics.transportrequest')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsProviderProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fleet_name', models.CharField(default='Kisan Freight Carrier Network', max_length=150)),
                ('fleet_size', models.PositiveIntegerField(default=45)),
                ('license_number', models.CharField(default='AGRI-LOG-LIC-9982', max_length=50)),
                ('service_states', models.CharField(default='Haryana, Punjab, Rajasthan, Uttar Pradesh', max_length=200)),
                ('contact_phone', models.CharField(default='+91 94160 55421', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
