# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auction_code', models.CharField(default='LOT-2026-8812', max_length=50)),
                ('crop_name', models.CharField(default='Wheat (Sharbati HD-3086)', max_length=150)),
                ('crop_name_hi', models.CharField(blank=True, default='गेहूं (सरबती एचडी-3086)', max_length=150, null=True)),
                ('variety', models.CharField(default='HD-3086 Certified', max_length=100)),
                ('quality_grade', models.CharField(default='Grade A (Assayed)', max_length=50)),
                ('moisture_percentage', models.DecimalField(decimal_places=2, default=11.4, max_digits=5)),
                ('quantity_mt', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('reserve_price', models.DecimalField(decimal_places=2, default=2450.0, max_digits=10)),
                ('current_highest_bid', models.DecimalField(decimal_places=2, default=2680.0, max_digits=10)),
                ('min_increment', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('seller_name', models.CharField(default='Sardar Balwinder Singh', max_length=150)),
                ('mandi_location', models.CharField(default='Karnal Central APMC', max_length=150)),
                ('district', models.CharField(default='Karnal', max_length=100)),
                ('state', models.CharField(default='Haryana', max_length=100)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='LIVE', max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_bids_count', models.PositiveIntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_created', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bidder_name', models.CharField(default='Adani Agri Logistics', max_length=150)),
                ('bidder_company', models.CharField(default='Adani Agri Logistics Ltd', max_length=150)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_winning', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction')),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
