# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPurchase',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='ORD-2026-9942', max_length=50)),
                ('crop_name', models.CharField(default='Wheat (Sharbati)', max_length=150)),
                ('seller_name', models.CharField(default='Sardar Balwinder Singh', max_length=150)),
                ('mandi_source', models.CharField(default='Karnal Central APMC', max_length=150)),
                ('quantity_quintals', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('rate_per_qtl', models.DecimalField(decimal_places=2, default=2680.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=1340000.0, max_digits=12)),
                ('status', models.CharField(choices=[('PAYMENT_HELD', 'Escrow Payment Deposited'), ('IN_TRANSIT', 'Freight In Transit'), ('DELIVERED', 'Delivered at Buyer Silo')], default='IN_TRANSIT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Adani Agri Logistics Ltd', max_length=150)),
                ('gstin', models.CharField(default='06AAACA1234B1Z5', max_length=20)),
                ('enam_license_no', models.CharField(default='ENAM-LIC-2025-882', max_length=50)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=5000000.0, max_digits=12)),
                ('verified_buyer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
