# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('token_string', models.CharField(default='AGM-TK-99482', max_length=50)),
                ('vehicle_number', models.CharField(default='HR-05-AB-7821', max_length=30)),
                ('driver_name', models.CharField(default='Harpreet Singh', max_length=100)),
                ('mandi_name', models.CharField(default='Karnal Central APMC', max_length=150)),
                ('gate_lane', models.CharField(default='Gate 01 - Heavy Lane', max_length=50)),
                ('operator_name', models.CharField(default='Ramesh Chand (Operator)', max_length=100)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted to Yard'), ('REJECTED', 'Entry Denied'), ('EXITED', 'Discharged')], default='ADMITTED', max_length=30)),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('qr_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_entries', to='tokens.qrtoken')),
            ],
        ),
        migrations.CreateModel(
            name='WeighmentSlip',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tola_parchi_number', models.CharField(max_length=50, unique=True)),
                ('token_string', models.CharField(default='AGM-TK-99482', max_length=50)),
                ('farmer_name', models.CharField(default='Sardar Harpreet Singh', max_length=150)),
                ('commodity', models.CharField(default='Wheat (Sharbati)', max_length=150)),
                ('vehicle_number', models.CharField(default='HR-05-AB-7821', max_length=30)),
                ('weighbridge_name', models.CharField(default='Dharam Kanta WB-01 (Karnal)', max_length=100)),
                ('operator_name', models.CharField(default='Sunil Kumar', max_length=100)),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, default=24580.0, max_digits=10)),
                ('tare_weight_kg', models.DecimalField(decimal_places=2, default=6580.0, max_digits=10)),
                ('net_weight_kg', models.DecimalField(decimal_places=2, default=18000.0, max_digits=10)),
                ('net_weight_quintals', models.DecimalField(decimal_places=2, default=180.0, max_digits=10)),
                ('gross_time', models.DateTimeField(auto_now_add=True)),
                ('tare_time', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('digital_signature', models.CharField(default='DIGI-WEIGH-KARNAL-APMC-9942', max_length=150)),
                ('gate_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slips', to='operations.gateentry')),
            ],
        ),
    ]
