# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(default='Sardar Harpreet Singh', max_length=150)),
                ('farmer_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('crop_name', models.CharField(default='Wheat (Sharbati)', max_length=150)),
                ('crop_hi', models.CharField(blank=True, default='गेहूं (सरबती)', max_length=150, null=True)),
                ('variety', models.CharField(default='HD-3086 Certified', max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, default=180.0, max_digits=10)),
                ('unit', models.CharField(default='Quintal', max_length=20)),
                ('expected_price', models.DecimalField(decimal_places=2, default=2580.0, max_digits=10)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('quality_grade', models.CharField(default='Grade A', max_length=50)),
                ('moisture_percentage', models.DecimalField(decimal_places=2, default=11.2, max_digits=5)),
                ('location', models.CharField(default='Karnal Central Mandi, Haryana', max_length=150)),
                ('description', models.TextField(blank=True, default='High-protein certified Sharbati wheat, optical NIR assayed.', null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Sale'), ('IN_AUCTION', 'In Live Auction'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=30)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(choices=[('Rabi', 'Rabi'), ('Kharif', 'Kharif'), ('Commercial', 'Commercial'), ('Zaid', 'Zaid')], default='Rabi', max_length=50)),
                ('icon', models.CharField(default='Wheat', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CropImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crop_photos/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crops.crop')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='crops.cropcategory'),
        ),
        migrations.AddField(
            model_name='crop',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crops_declared', to=settings.AUTH_USER_MODEL),
        ),
    ]
