# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('khasra_number', models.CharField(default='412/18', max_length=50)),
                ('khatauni_number', models.CharField(default='094-KH', max_length=50)),
                ('village', models.CharField(default='Gharaunda', max_length=100)),
                ('tehsil', models.CharField(default='Karnal', max_length=100)),
                ('district', models.CharField(default='Karnal', max_length=100)),
                ('state', models.CharField(default='Haryana', max_length=100)),
                ('area_acres', models.DecimalField(decimal_places=2, default=3.2, max_digits=6)),
                ('soil_type', models.CharField(default='Alluvial Loam', max_length=50)),
                ('irrigation_source', models.CharField(default='Tube Well & Canal', max_length=50)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kisan_credit_card', models.CharField(blank=True, default='KCC-HR-998241', max_length=50, null=True)),
                ('total_land_acres', models.DecimalField(decimal_places=2, default=5.5, max_digits=6)),
                ('soil_health_card_id', models.CharField(blank=True, default='SHC-2025-4120', max_length=50, null=True)),
                ('bank_account_no', models.CharField(default='982100341829', max_length=30)),
                ('bank_ifsc', models.CharField(default='PUNB0021400', max_length=20)),
                ('bank_name', models.CharField(default='Punjab National Bank', max_length=100)),
                ('dbt_linked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
