# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='CWC Regional Silo Complex 04', max_length=150)),
                ('code', models.CharField(default='CWC-PNP-04', max_length=50, unique=True)),
                ('manager_name', models.CharField(default='V. K. Aggarwal (Warehouse Superintendent)', max_length=150)),
                ('state', models.CharField(default='Haryana', max_length=100)),
                ('district', models.CharField(default='Panipat', max_length=100)),
                ('location_address', models.TextField(default='Sector 25 Phase II, Industrial Area, Panipat')),
                ('total_capacity_mt', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('current_stock_mt', models.DecimalField(decimal_places=2, default=38420.0, max_digits=12)),
                ('available_capacity_mt', models.DecimalField(decimal_places=2, default=11580.0, max_digits=12)),
                ('temperature_celsius', models.DecimalField(decimal_places=1, default=21.4, max_digits=4)),
                ('relative_humidity_pct', models.DecimalField(decimal_places=1, default=58.2, max_digits=4)),
                ('silos_count', models.PositiveIntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_id', models.CharField(max_length=50, unique=True)),
                ('movement_type', models.CharField(choices=[('STOCK_IN', 'Stock In (Procurement Arrival)'), ('STOCK_OUT', 'Stock Out (PDS / Buyer Dispatch)'), ('TRANSFER', 'Inter-Warehouse Transfer')], default='STOCK_IN', max_length=30)),
                ('commodity', models.CharField(default='Wheat (Grade A)', max_length=150)),
                ('quantity_mt', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('source_mandi_or_hub', models.CharField(default='Karnal Central APMC', max_length=150)),
                ('destination_hub', models.CharField(default='CWC Panipat Silo 04', max_length=150)),
                ('truck_number', models.CharField(default='HR-05-AB-7821', max_length=30)),
                ('grn_receipt_number', models.CharField(default='GRN-2026-99120', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commodity', models.CharField(default='Wheat (Grade A FAQ)', max_length=150)),
                ('silo_number', models.CharField(default='Silo B-03', max_length=50)),
                ('quantity_stored_mt', models.DecimalField(decimal_places=2, default=4500.0, max_digits=10)),
                ('quality_grade', models.CharField(default='Grade A', max_length=50)),
                ('moisture_percentage', models.DecimalField(decimal_places=2, default=11.2, max_digits=5)),
                ('last_fumigation_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='warehouses.warehouse')),
            ],
        ),
    ]
