# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(max_length=50, unique=True)),
                ('recipient_name', models.CharField(default='Sardar Harpreet Singh', max_length=150)),
                ('recipient_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('recipient_aadhaar', models.CharField(default='XXXX-XXXX-4821', max_length=20)),
                ('bank_account', models.CharField(default='982100341829', max_length=30)),
                ('bank_ifsc', models.CharField(default='PUNB0021400', max_length=20)),
                ('bank_name', models.CharField(default='Punjab National Bank', max_length=100)),
                ('commodity', models.CharField(default='Wheat (Sharbati Grade A)', max_length=150)),
                ('quantity_quintals', models.DecimalField(decimal_places=2, default=180.0, max_digits=10)),
                ('rate_per_qtl', models.DecimalField(decimal_places=2, default=2425.0, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=436500.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_payout_amount', models.DecimalField(decimal_places=2, default=436500.0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('DBT', 'Direct Benefit Transfer (NPCI Aadhaar Bridge)'), ('PFMS', 'Public Financial Management System'), ('BANK_TRANSFER', 'NEFT / RTGS Bank Transfer'), ('UPI', 'UPI Mandi Instant')], default='DBT', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('PROCESSING', 'Processing via PFMS'), ('COMPLETED', 'Completed & Credited'), ('FAILED', 'Failed')], default='COMPLETED', max_length=30)),
                ('utr_number', models.CharField(default='RBI056984210992', max_length=50)),
                ('pfms_ref_no', models.CharField(default='PFMS-AGRI-2026-99418', max_length=50)),
                ('disbursed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
