# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=150)),
                ('crop_name_hi', models.CharField(blank=True, max_length=150, null=True)),
                ('variety', models.CharField(default='Standard FAQ', max_length=150)),
                ('mandi_name', models.CharField(max_length=150)),
                ('mandi_name_hi', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('msp_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modal_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_market_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('highest_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrivals_today', models.CharField(default='1,420 MT', max_length=50)),
                ('status_tag', models.CharField(default='ABOVE MSP', max_length=100)),
                ('trend', models.CharField(choices=[('up', 'Upward'), ('down', 'Downward'), ('stable', 'Stable')], default='up', max_length=10)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MSPPrice',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_code', models.CharField(max_length=50, unique=True)),
                ('crop_name', models.CharField(max_length=150)),
                ('crop_name_hi', models.CharField(blank=True, max_length=150, null=True)),
                ('season', models.CharField(default='Rabi', max_length=50)),
                ('year', models.CharField(default='2025-2026', max_length=20)),
                ('msp_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('standard_moisture_limit', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=150)),
                ('mandi_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msp_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_mt', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
            ],
        ),
    ]
