# Generated by Django 4.2.30 on 2026-08-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementCenter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('name_hi', models.CharField(blank=True, max_length=150, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField(default='Main APMC Yard')),
                ('daily_capacity_mt', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('operational_status', models.CharField(choices=[('ACTIVE', 'Active & Procuring'), ('MAINTENANCE', 'Under Maintenance'), ('FULL', 'Capacity Full')], default='ACTIVE', max_length=30)),
                ('contact_phone', models.CharField(default='1800-180-1551', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, default=29.6857, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=76.9905, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_centers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CenterCapacity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('commodity', models.CharField(default='Wheat', max_length=100)),
                ('total_quota_mt', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10)),
                ('booked_quota_mt', models.DecimalField(decimal_places=2, default=1840.0, max_digits=10)),
                ('procured_today_mt', models.DecimalField(decimal_places=2, default=1250.0, max_digits=10)),
                ('available_slots', models.PositiveIntegerField(default=45)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_capacities', to='centers.procurementcenter')),
            ],
        ),
    ]
